### ISSUE TITLE
Improve README: Add Project-Specific Documentation

### ISSUE THREAD

**Issue by ay-bh** [ay-bh/CICD-demo#1]
**Is your feature request related to a problem? Please describe.**
The current README lacks specific information about our calculator project. It only contains generic Next.js setup instructions, which doesn't help users understand what our project does or how to use it. This makes it difficult for new users or contributors to get started with our calculator application.

**Describe the solution you'd like**
We need a comprehensive README that provides clear information about our Next.js calculator project. The improved documentation should include:

1. A brief project description and its main features
2. Installation instructions specific to our project
3. Usage guide with examples of how to use the calculator
4. Information about the project structure
5. Technologies used (Next.js, any additional libraries)
6. How to contribute to the project
7. License information

**Describe alternatives you've considered**
1. Creating a separate documentation website, but this might be overkill for a simple calculator project.
2. Adding inline comments in the code, but this doesn't provide an easy overview for new users.
3. Writing a wiki page, but having the information directly in the README is more accessible.

**Additional context**
The current README is the default one generated by create-next-app. While it provides useful information about Next.js, it doesn't give any context about our specific calculator project. Improving the README will make our project more user-friendly and potentially attract more users and contributors.

**Comment by ViditJain123** [comment]
Hey, can work on this issue?

**Comment by ay-bh** [comment]
Sure.
